How to normalize an array in NumPy?

https://stackoverflow.com/questions/21030391/how-to-normalize-an-array-in-numpy

In [1]:
import numpy as np
from sklearn.preprocessing import normalize

x = np.random.rand(10)*6
norm1 = x / np.linalg.norm(x)
norm2 = normalize(x[:,np.newaxis], axis=0).ravel()
print(np.all(norm1 == norm2))

True


In [3]:
x

array([0.5237381 , 3.92121542, 4.53694939, 1.22676326, 1.27761976,
       2.48141115, 3.70827533, 1.47384029, 1.14541581, 0.53247493])

In [2]:
norm1

array([0.06595977, 0.49383931, 0.57138508, 0.15449902, 0.1609039 ,
       0.31250983, 0.46702156, 0.18561599, 0.14425409, 0.06706009])

In [5]:
y = np.array([3,4])
y

array([3, 4])

In [6]:
norm_y = y / np.linalg.norm(y)
norm_y

array([0.6, 0.8])

In [2]:
import numpy as np

In [3]:
a = np.random.randint(5,size=(3,4))

In [4]:
a

array([[1, 3, 4, 3],
       [4, 4, 4, 3],
       [2, 3, 4, 2]])

In [5]:
b = np.linalg.norm(a,ord=2,axis=1,keepdims=True) # 二范数
b

array([[5.91607978],
       [7.54983444],
       [5.74456265]])

In [6]:
np.sqrt(35)

5.916079783099616

In [7]:
c = a/b
c

array([[0.16903085, 0.50709255, 0.6761234 , 0.50709255],
       [0.52981294, 0.52981294, 0.52981294, 0.39735971],
       [0.34815531, 0.52223297, 0.69631062, 0.34815531]])